### ISSUE TITLE
System crash after connection to local DB failure

### ISSUE THREAD

**Issue by dmazzer** [dmazzer/nors#15]
If the connection to local DB fails, the system does not recover from exception and stop trying to reconnect.

```
Exception in thread CheckForLocalData:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/mazzer/nors/remote/client/client.py", line 96, in check_for_local_data_worker
    self._update_remote()
  File "/home/mazzer/nors/remote/client/client.py", line 105, in _update_remote
    data_to_send = self.local_storage.get_first()
  File "/home/mazzer/nors/remote/localstorage/localstorage.py", line 44, in get_first
    result = self.local_dao.get_first_n_itens(self.local_db_sensor_streams_name, 1)
  File "/home/mazzer/nors/remote/localstorage/dao.py", line 60, in get_first_n_itens
    return self.find(CollectionName, SearchLimit=numberOfItems, Sort=[('_id', pymongo.ASCENDING), ])
  File "/home/mazzer/nors/remote/localstorage/dao.py", line 74, in find
    return self._find_with_sort_without_string(CollectionName, SearchLimit, Sort)
  File "/home/mazzer/nors/remote/localstorage/dao.py", line 83, in _find_with_sort_without_string
    for i in collected:
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1090, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1012, in _refresh
    self.__read_concern))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 850, in __send_message
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 781, in _send_message_with_response
    server = topology.select_server(selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 142, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 118, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

```

**Comment by dmazzer** [comment]
Try this:
https://stackoverflow.com/questions/9837631/how-to-check-in-pymongo-is-connection-is-still-alive
